//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Torq.WPF.SalaryService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Salary", Namespace="http://schemas.datacontract.org/2004/07/Torq.Models.Objects")]
    [System.SerializableAttribute()]
    public partial class Salary : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Torq.WPF.SalaryService.Employee EmployeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SalaryTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Torq.WPF.SalaryService.Schema[] SchemasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Torq.WPF.SalaryService.Employee Employee {
            get {
                return this.EmployeeField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeField, value) != true)) {
                    this.EmployeeField = value;
                    this.RaisePropertyChanged("Employee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SalaryType {
            get {
                return this.SalaryTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.SalaryTypeField, value) != true)) {
                    this.SalaryTypeField = value;
                    this.RaisePropertyChanged("SalaryType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Torq.WPF.SalaryService.Schema[] Schemas {
            get {
                return this.SchemasField;
            }
            set {
                if ((object.ReferenceEquals(this.SchemasField, value) != true)) {
                    this.SchemasField = value;
                    this.RaisePropertyChanged("Schemas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://schemas.datacontract.org/2004/07/Torq.Models.Objects")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsOnlineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Torq.WPF.SalaryService.Role RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Torq.WPF.SalaryService.Schema[] SchemasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsOnline {
            get {
                return this.IsOnlineField;
            }
            set {
                if ((this.IsOnlineField.Equals(value) != true)) {
                    this.IsOnlineField = value;
                    this.RaisePropertyChanged("IsOnline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Torq.WPF.SalaryService.Role Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Torq.WPF.SalaryService.Schema[] Schemas {
            get {
                return this.SchemasField;
            }
            set {
                if ((object.ReferenceEquals(this.SchemasField, value) != true)) {
                    this.SchemasField = value;
                    this.RaisePropertyChanged("Schemas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Schema", Namespace="http://schemas.datacontract.org/2004/07/Torq.Models.Objects")]
    [System.SerializableAttribute()]
    public partial class Schema : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ClockedInField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Torq.WPF.SalaryService.Employee EmployeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Torq.WPF.SalaryService.Salary SalaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ClockedIn {
            get {
                return this.ClockedInField;
            }
            set {
                if ((this.ClockedInField.Equals(value) != true)) {
                    this.ClockedInField = value;
                    this.RaisePropertyChanged("ClockedIn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Torq.WPF.SalaryService.Employee Employee {
            get {
                return this.EmployeeField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeField, value) != true)) {
                    this.EmployeeField = value;
                    this.RaisePropertyChanged("Employee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Torq.WPF.SalaryService.Salary Salary {
            get {
                return this.SalaryField;
            }
            set {
                if ((object.ReferenceEquals(this.SalaryField, value) != true)) {
                    this.SalaryField = value;
                    this.RaisePropertyChanged("Salary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Role", Namespace="http://schemas.datacontract.org/2004/07/Torq.Models.Objects")]
    [System.SerializableAttribute()]
    public partial class Role : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Torq.WPF.SalaryService.Employee[] EmployeesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Torq.WPF.SalaryService.Employee[] Employees {
            get {
                return this.EmployeesField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeesField, value) != true)) {
                    this.EmployeesField = value;
                    this.RaisePropertyChanged("Employees");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SalaryService.ISalaryService")]
    public interface ISalaryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaryService/CreateSchema", ReplyAction="http://tempuri.org/ISalaryService/CreateSchemaResponse")]
        Torq.WPF.SalaryService.Salary CreateSchema(Torq.WPF.SalaryService.Salary salary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaryService/CreateSchema", ReplyAction="http://tempuri.org/ISalaryService/CreateSchemaResponse")]
        System.Threading.Tasks.Task<Torq.WPF.SalaryService.Salary> CreateSchemaAsync(Torq.WPF.SalaryService.Salary salary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaryService/GetSalaries", ReplyAction="http://tempuri.org/ISalaryService/GetSalariesResponse")]
        Torq.WPF.SalaryService.Salary[] GetSalaries();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaryService/GetSalaries", ReplyAction="http://tempuri.org/ISalaryService/GetSalariesResponse")]
        System.Threading.Tasks.Task<Torq.WPF.SalaryService.Salary[]> GetSalariesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaryService/GetSalaryById", ReplyAction="http://tempuri.org/ISalaryService/GetSalaryByIdResponse")]
        Torq.WPF.SalaryService.Salary GetSalaryById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaryService/GetSalaryById", ReplyAction="http://tempuri.org/ISalaryService/GetSalaryByIdResponse")]
        System.Threading.Tasks.Task<Torq.WPF.SalaryService.Salary> GetSalaryByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaryService/UpdateSalary", ReplyAction="http://tempuri.org/ISalaryService/UpdateSalaryResponse")]
        Torq.WPF.SalaryService.Salary UpdateSalary(Torq.WPF.SalaryService.Salary salary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaryService/UpdateSalary", ReplyAction="http://tempuri.org/ISalaryService/UpdateSalaryResponse")]
        System.Threading.Tasks.Task<Torq.WPF.SalaryService.Salary> UpdateSalaryAsync(Torq.WPF.SalaryService.Salary salary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaryService/RemoveSalary", ReplyAction="http://tempuri.org/ISalaryService/RemoveSalaryResponse")]
        void RemoveSalary(Torq.WPF.SalaryService.Salary salary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaryService/RemoveSalary", ReplyAction="http://tempuri.org/ISalaryService/RemoveSalaryResponse")]
        System.Threading.Tasks.Task RemoveSalaryAsync(Torq.WPF.SalaryService.Salary salary);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISalaryServiceChannel : Torq.WPF.SalaryService.ISalaryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SalaryServiceClient : System.ServiceModel.ClientBase<Torq.WPF.SalaryService.ISalaryService>, Torq.WPF.SalaryService.ISalaryService {
        
        public SalaryServiceClient() {
        }
        
        public SalaryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SalaryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalaryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalaryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Torq.WPF.SalaryService.Salary CreateSchema(Torq.WPF.SalaryService.Salary salary) {
            return base.Channel.CreateSchema(salary);
        }
        
        public System.Threading.Tasks.Task<Torq.WPF.SalaryService.Salary> CreateSchemaAsync(Torq.WPF.SalaryService.Salary salary) {
            return base.Channel.CreateSchemaAsync(salary);
        }
        
        public Torq.WPF.SalaryService.Salary[] GetSalaries() {
            return base.Channel.GetSalaries();
        }
        
        public System.Threading.Tasks.Task<Torq.WPF.SalaryService.Salary[]> GetSalariesAsync() {
            return base.Channel.GetSalariesAsync();
        }
        
        public Torq.WPF.SalaryService.Salary GetSalaryById(int id) {
            return base.Channel.GetSalaryById(id);
        }
        
        public System.Threading.Tasks.Task<Torq.WPF.SalaryService.Salary> GetSalaryByIdAsync(int id) {
            return base.Channel.GetSalaryByIdAsync(id);
        }
        
        public Torq.WPF.SalaryService.Salary UpdateSalary(Torq.WPF.SalaryService.Salary salary) {
            return base.Channel.UpdateSalary(salary);
        }
        
        public System.Threading.Tasks.Task<Torq.WPF.SalaryService.Salary> UpdateSalaryAsync(Torq.WPF.SalaryService.Salary salary) {
            return base.Channel.UpdateSalaryAsync(salary);
        }
        
        public void RemoveSalary(Torq.WPF.SalaryService.Salary salary) {
            base.Channel.RemoveSalary(salary);
        }
        
        public System.Threading.Tasks.Task RemoveSalaryAsync(Torq.WPF.SalaryService.Salary salary) {
            return base.Channel.RemoveSalaryAsync(salary);
        }
    }
}
