//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Torq.WPF.SchemaService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Schema", Namespace="http://schemas.datacontract.org/2004/07/Torq.Models.Objects")]
    [System.SerializableAttribute()]
    public partial class Schema : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ClockedInField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Torq.WPF.SchemaService.Employee EmployeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Torq.WPF.SchemaService.Salary SalaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ClockedIn {
            get {
                return this.ClockedInField;
            }
            set {
                if ((this.ClockedInField.Equals(value) != true)) {
                    this.ClockedInField = value;
                    this.RaisePropertyChanged("ClockedIn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Torq.WPF.SchemaService.Employee Employee {
            get {
                return this.EmployeeField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeField, value) != true)) {
                    this.EmployeeField = value;
                    this.RaisePropertyChanged("Employee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Torq.WPF.SchemaService.Salary Salary {
            get {
                return this.SalaryField;
            }
            set {
                if ((object.ReferenceEquals(this.SalaryField, value) != true)) {
                    this.SalaryField = value;
                    this.RaisePropertyChanged("Salary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://schemas.datacontract.org/2004/07/Torq.Models.Objects")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsOnlineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Torq.WPF.SchemaService.Schema RoleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Torq.WPF.SchemaService.Schema[] SchemasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsOnline {
            get {
                return this.IsOnlineField;
            }
            set {
                if ((this.IsOnlineField.Equals(value) != true)) {
                    this.IsOnlineField = value;
                    this.RaisePropertyChanged("IsOnline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Torq.WPF.SchemaService.Schema RoleId {
            get {
                return this.RoleIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleIdField, value) != true)) {
                    this.RoleIdField = value;
                    this.RaisePropertyChanged("RoleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Torq.WPF.SchemaService.Schema[] Schemas {
            get {
                return this.SchemasField;
            }
            set {
                if ((object.ReferenceEquals(this.SchemasField, value) != true)) {
                    this.SchemasField = value;
                    this.RaisePropertyChanged("Schemas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Salary", Namespace="http://schemas.datacontract.org/2004/07/Torq.Models.Objects")]
    [System.SerializableAttribute()]
    public partial class Salary : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Torq.WPF.SchemaService.Employee EmployeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SalaryTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Torq.WPF.SchemaService.Schema[] SchemasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Torq.WPF.SchemaService.Employee Employee {
            get {
                return this.EmployeeField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeField, value) != true)) {
                    this.EmployeeField = value;
                    this.RaisePropertyChanged("Employee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SalaryType {
            get {
                return this.SalaryTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.SalaryTypeField, value) != true)) {
                    this.SalaryTypeField = value;
                    this.RaisePropertyChanged("SalaryType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Torq.WPF.SchemaService.Schema[] Schemas {
            get {
                return this.SchemasField;
            }
            set {
                if ((object.ReferenceEquals(this.SchemasField, value) != true)) {
                    this.SchemasField = value;
                    this.RaisePropertyChanged("Schemas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SchemaService.ISchemaService")]
    public interface ISchemaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchemaService/CreateSchema", ReplyAction="http://tempuri.org/ISchemaService/CreateSchemaResponse")]
        Torq.WPF.SchemaService.Schema CreateSchema(Torq.WPF.SchemaService.Schema schema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchemaService/CreateSchema", ReplyAction="http://tempuri.org/ISchemaService/CreateSchemaResponse")]
        System.Threading.Tasks.Task<Torq.WPF.SchemaService.Schema> CreateSchemaAsync(Torq.WPF.SchemaService.Schema schema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchemaService/GetSchemaById", ReplyAction="http://tempuri.org/ISchemaService/GetSchemaByIdResponse")]
        Torq.WPF.SchemaService.Schema GetSchemaById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchemaService/GetSchemaById", ReplyAction="http://tempuri.org/ISchemaService/GetSchemaByIdResponse")]
        System.Threading.Tasks.Task<Torq.WPF.SchemaService.Schema> GetSchemaByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchemaService/GetSchemas", ReplyAction="http://tempuri.org/ISchemaService/GetSchemasResponse")]
        Torq.WPF.SchemaService.Schema[] GetSchemas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchemaService/GetSchemas", ReplyAction="http://tempuri.org/ISchemaService/GetSchemasResponse")]
        System.Threading.Tasks.Task<Torq.WPF.SchemaService.Schema[]> GetSchemasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchemaService/RemoveSchema", ReplyAction="http://tempuri.org/ISchemaService/RemoveSchemaResponse")]
        void RemoveSchema(Torq.WPF.SchemaService.Schema schema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchemaService/RemoveSchema", ReplyAction="http://tempuri.org/ISchemaService/RemoveSchemaResponse")]
        System.Threading.Tasks.Task RemoveSchemaAsync(Torq.WPF.SchemaService.Schema schema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchemaService/UpdateRole", ReplyAction="http://tempuri.org/ISchemaService/UpdateRoleResponse")]
        Torq.WPF.SchemaService.Schema UpdateRole(Torq.WPF.SchemaService.Schema schema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchemaService/UpdateRole", ReplyAction="http://tempuri.org/ISchemaService/UpdateRoleResponse")]
        System.Threading.Tasks.Task<Torq.WPF.SchemaService.Schema> UpdateRoleAsync(Torq.WPF.SchemaService.Schema schema);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISchemaServiceChannel : Torq.WPF.SchemaService.ISchemaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SchemaServiceClient : System.ServiceModel.ClientBase<Torq.WPF.SchemaService.ISchemaService>, Torq.WPF.SchemaService.ISchemaService {
        
        public SchemaServiceClient() {
        }
        
        public SchemaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SchemaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SchemaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SchemaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Torq.WPF.SchemaService.Schema CreateSchema(Torq.WPF.SchemaService.Schema schema) {
            return base.Channel.CreateSchema(schema);
        }
        
        public System.Threading.Tasks.Task<Torq.WPF.SchemaService.Schema> CreateSchemaAsync(Torq.WPF.SchemaService.Schema schema) {
            return base.Channel.CreateSchemaAsync(schema);
        }
        
        public Torq.WPF.SchemaService.Schema GetSchemaById(int id) {
            return base.Channel.GetSchemaById(id);
        }
        
        public System.Threading.Tasks.Task<Torq.WPF.SchemaService.Schema> GetSchemaByIdAsync(int id) {
            return base.Channel.GetSchemaByIdAsync(id);
        }
        
        public Torq.WPF.SchemaService.Schema[] GetSchemas() {
            return base.Channel.GetSchemas();
        }
        
        public System.Threading.Tasks.Task<Torq.WPF.SchemaService.Schema[]> GetSchemasAsync() {
            return base.Channel.GetSchemasAsync();
        }
        
        public void RemoveSchema(Torq.WPF.SchemaService.Schema schema) {
            base.Channel.RemoveSchema(schema);
        }
        
        public System.Threading.Tasks.Task RemoveSchemaAsync(Torq.WPF.SchemaService.Schema schema) {
            return base.Channel.RemoveSchemaAsync(schema);
        }
        
        public Torq.WPF.SchemaService.Schema UpdateRole(Torq.WPF.SchemaService.Schema schema) {
            return base.Channel.UpdateRole(schema);
        }
        
        public System.Threading.Tasks.Task<Torq.WPF.SchemaService.Schema> UpdateRoleAsync(Torq.WPF.SchemaService.Schema schema) {
            return base.Channel.UpdateRoleAsync(schema);
        }
    }
}
