//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Torq.MVC.SalariesService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SalariesService.ISalaryService")]
    public interface ISalaryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaryService/CreateSalary", ReplyAction="http://tempuri.org/ISalaryService/CreateSalaryResponse")]
        Torq.Models.Objects.Salary CreateSalary(Torq.Models.Objects.Salary salary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaryService/CreateSalary", ReplyAction="http://tempuri.org/ISalaryService/CreateSalaryResponse")]
        System.Threading.Tasks.Task<Torq.Models.Objects.Salary> CreateSalaryAsync(Torq.Models.Objects.Salary salary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaryService/GetSalaries", ReplyAction="http://tempuri.org/ISalaryService/GetSalariesResponse")]
        Torq.Models.Objects.Salary[] GetSalaries();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaryService/GetSalaries", ReplyAction="http://tempuri.org/ISalaryService/GetSalariesResponse")]
        System.Threading.Tasks.Task<Torq.Models.Objects.Salary[]> GetSalariesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaryService/GetSalaryById", ReplyAction="http://tempuri.org/ISalaryService/GetSalaryByIdResponse")]
        Torq.Models.Objects.Salary GetSalaryById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaryService/GetSalaryById", ReplyAction="http://tempuri.org/ISalaryService/GetSalaryByIdResponse")]
        System.Threading.Tasks.Task<Torq.Models.Objects.Salary> GetSalaryByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaryService/UpdateSalary", ReplyAction="http://tempuri.org/ISalaryService/UpdateSalaryResponse")]
        Torq.Models.Objects.Salary UpdateSalary(Torq.Models.Objects.Salary salary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaryService/UpdateSalary", ReplyAction="http://tempuri.org/ISalaryService/UpdateSalaryResponse")]
        System.Threading.Tasks.Task<Torq.Models.Objects.Salary> UpdateSalaryAsync(Torq.Models.Objects.Salary salary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaryService/RemoveSalary", ReplyAction="http://tempuri.org/ISalaryService/RemoveSalaryResponse")]
        void RemoveSalary(Torq.Models.Objects.Salary salary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaryService/RemoveSalary", ReplyAction="http://tempuri.org/ISalaryService/RemoveSalaryResponse")]
        System.Threading.Tasks.Task RemoveSalaryAsync(Torq.Models.Objects.Salary salary);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISalaryServiceChannel : Torq.MVC.SalariesService.ISalaryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SalaryServiceClient : System.ServiceModel.ClientBase<Torq.MVC.SalariesService.ISalaryService>, Torq.MVC.SalariesService.ISalaryService {
        
        public SalaryServiceClient() {
        }
        
        public SalaryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SalaryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalaryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalaryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Torq.Models.Objects.Salary CreateSalary(Torq.Models.Objects.Salary salary) {
            return base.Channel.CreateSalary(salary);
        }
        
        public System.Threading.Tasks.Task<Torq.Models.Objects.Salary> CreateSalaryAsync(Torq.Models.Objects.Salary salary) {
            return base.Channel.CreateSalaryAsync(salary);
        }
        
        public Torq.Models.Objects.Salary[] GetSalaries() {
            return base.Channel.GetSalaries();
        }
        
        public System.Threading.Tasks.Task<Torq.Models.Objects.Salary[]> GetSalariesAsync() {
            return base.Channel.GetSalariesAsync();
        }
        
        public Torq.Models.Objects.Salary GetSalaryById(int id) {
            return base.Channel.GetSalaryById(id);
        }
        
        public System.Threading.Tasks.Task<Torq.Models.Objects.Salary> GetSalaryByIdAsync(int id) {
            return base.Channel.GetSalaryByIdAsync(id);
        }
        
        public Torq.Models.Objects.Salary UpdateSalary(Torq.Models.Objects.Salary salary) {
            return base.Channel.UpdateSalary(salary);
        }
        
        public System.Threading.Tasks.Task<Torq.Models.Objects.Salary> UpdateSalaryAsync(Torq.Models.Objects.Salary salary) {
            return base.Channel.UpdateSalaryAsync(salary);
        }
        
        public void RemoveSalary(Torq.Models.Objects.Salary salary) {
            base.Channel.RemoveSalary(salary);
        }
        
        public System.Threading.Tasks.Task RemoveSalaryAsync(Torq.Models.Objects.Salary salary) {
            return base.Channel.RemoveSalaryAsync(salary);
        }
    }
}
